social_media/account/urls.py
from django.urls import path
from . import views


app_name = 'account'

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user-register'),
    path('login/', views.UserLoginView.as_view(), name='user-login'),
    path('logout/', views.UserLogoutView.as_view(), name='user-logout'),
    path('profile/<int:user_id>/', views.UserProfileView.as_view(), name='user-profile'),
    path('reset/', views.UserPasswordRestView.as_view(), name='password-reset'),
    path('reset/done/', views.UserPasswordResetDoneView.as_view(), name='password-reset-done'),
    path('confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(), name='password-reset-confirm'),
    path('confirm/complete/', views.UserPasswordResetCompleteView.as_view(), name='password-reset-complete'),
    path('follow/<int:user_id>/', views.UserFollowView.as_view(), name='user-follow'),
    path('unfollow/<int:user_id>/', views.UserUnFollowView.as_view(), name='user-unfollow'),
]

social_media/home/urls.py
from django.urls import path
from . import views



app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('post/<int:post_id>/<slug:slug>/', views.PostDetailView.as_view(), name='post-detail'),
    path('post/delete/<int:post_id>/', views.PostDeleteView.as_view() , name = 'post-delete'),
    path('post/update/<int:post_id>/', views.PostUpdateView.as_view() , name = 'post-update'),
    path('post/create/', views.PostCreateView.as_view() , name = 'post-create'),
]

social_media/social_media/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls', namespace='home')),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
]

social_media/templates/inc/messages.html
{% if messages %}

    {% for msg in messages %}
    
        <p class="alert alert-{{ msg.tags }}"> {{ msg }} </p>
    {% endfor %}
{% endif %}

social_media/templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <div class="navbar-nav">
        <a class="navbar-brand" href="{% url 'home:home' %}">home</a>
        {% if request.user.is_authenticated %}
        
          <a class="navbar-brand" href="{% url 'account:user-logout' %}">Logout</a>
          <a class="navbar-brand" href="{% url 'account:user-profile' request.user.id %}">profile</a>
        {% else %}
          <a class="navbar-brand" href="{% url 'account:user-register' %}">Register</a>
          <a class="navbar-brand" href="{% url 'account:user-login' %}">Login</a>
        
        {% endif %}
      </div>
    </div>
  </nav>