social_media/account/urls.py
from django.urls import path
from . import views


app_name = 'account'

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user-register'),
    path('login/', views.UserLoginView.as_view(), name='user-login'),
    path('logout/', views.UserLogoutView.as_view(), name='user-logout'),
    path('profile/<int:user_id>/', views.UserProfileView.as_view(), name='user-profile'),
    path('reset/', views.UserPasswordRestView.as_view(), name='password-reset'),
    path('reset/done/', views.UserPasswordResetDoneView.as_view(), name='password-reset-done'),
    path('confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(), name='password-reset-confirm'),
    path('confirm/complete/', views.UserPasswordResetCompleteView.as_view(), name='password-reset-complete'),
    path('follow/<int:user_id>/', views.UserFollowView.as_view(), name='user-follow'),
    path('unfollow/<int:user_id>/', views.UserUnFollowView.as_view(), name='user-unfollow'),
]

social_media/home/urls.py
from django.urls import path
from . import views



app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('post/<int:post_id>/<slug:slug>/', views.PostDetailView.as_view(), name='post-detail'),
    path('post/delete/<int:post_id>/', views.PostDeleteView.as_view() , name = 'post-delete'),
    path('post/update/<int:post_id>/', views.PostUpdateView.as_view() , name = 'post-update'),
    path('post/create/', views.PostCreateView.as_view() , name = 'post-create'),
]

social_media/social_media/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls', namespace='home')),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
]

social_media/home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    body = models.TextField()
    slug = models.SlugField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    
    
    def __str__(self):
        return f'{self.slug}'
    
    
    
    def get_absolute_url(self):
        return reverse("home:post-detail", args=(self.id, self.slug))
    

social_media/home/forms.py
from django import forms
from .models import Post




class PostCreateUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('body',)

social_media/home/views.py
from django import http
from django.shortcuts import redirect, render, get_object_or_404
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.utils.text import slugify
from .forms import PostCreateUpdateForm
from . import models
# Create your views here.

class HomeView(View):
    
    def get(self, request, *args, **kwargs):
        posts = models.Post.objects.order_by('-created')
        return render(request, 'home/index.html', {'posts': posts})
    


class PostDetailView(View):
    
    def get(self, request, post_id, slug):
        post = get_object_or_404(models.Post, id=post_id, slug=slug)
        return render(request, 'home/detail.html', {'post': post})
    
class PostDeleteView(LoginRequiredMixin, View):
    
    def get(self, request, post_id):
        post = get_object_or_404(models.Post, id=post_id)
        if post.user.id == request.user.id:
            post.delete()
            messages.success(request, f'post deleted successfully',extra_tags='success')
        else:
            messages.error(request, f'you cant delete this post',extra_tags='danger')
        
        return redirect('home:home')
    
class PostUpdateView(LoginRequiredMixin, View):
    
    form_class = PostCreateUpdateForm
    
    def setup(self, request, *args, **kwargs):
        self.post_instance = get_object_or_404(models.Post,id=kwargs['post_id'])
        return super().setup(request, *args, **kwargs)
    
    def dispatch(self, request, *args, **kwargs):
        post = self.post_instance
        if not post.user.id == request.user.id:
            messages.error(request, f'you cant update this post',extra_tags='danger')
            return redirect('home:home')        
        return super().dispatch(request, *args, **kwargs)
    
    def get(self, request, *args, **kwargs):
        post = self.post_instance
        form = self.form_class(instance=post)
        return render(request, 'home/update.html', {'form': form})
    
    def post(self, request, *args, **kwargs):
        post = self.post_instance
        form = self.form_class(request.POST, instance=post)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(form.cleaned_data['body'][:30])
            new_post.save()
            messages.success(request, f'post updated successfully',extra_tags='success')
            return redirect('home:post-detail', post.id, post.slug)
        

class PostCreateView(LoginRequiredMixin, View):
    form_class = PostCreateUpdateForm
    
    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, 'home/create.html', {'form': form})
    
    
    
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.user = request.user
            new_post.slug = slugify(form.cleaned_data['body'][:30])
            new_post.save()
            messages.success(request, f'post created successfully',extra_tags='success')
            return redirect('home:post-detail', new_post.id, new_post.slug)    
    

social_media/home/templates/home/create.html
{% extends 'base.html' %}

{% block title %}

    Create Post

{% endblock title %}



{% block content %}

<form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value='Create'>

</form>


{% endblock content %}

social_media/home/templates/home/detail.html
{% extends 'base.html' %}


{% block content %}

{% if request.user.id == post.user.id %}
    <a href='{% url 'home:post-delete' post.id %}', class='btn btn-danger'> Delete </a>
    <a href='{% url 'home:post-update' post.id %}', class='btn btn-info'> Update </a>
{% endif %}

<h3> created by: <a href='{% url 'account:user-profile' post.user.id %}'> {{ post.user.username }} </a> </h3>
<p> {{ post.updated|date:"Y-M-d H:i" }} </p>
<hr>

<p> {{ post.body }} </p>


{% endblock content %}

social_media/home/templates/home/index.html
{% extends 'base.html' %}

{% block title %}
    home page
{% endblock title %}


{% block content %}
    This is home page
    <p> You are logged in as user:  {{ request.user }} </p>

    <div class='card'>
    {% for post in posts %}
        <a href='{{ post.get_absolute_url }}' class='card-body'> {{ post.body|truncatewords:8 }} </a>
    
    
    {% endfor %}    
    
    
    </div>
{% endblock content %}

social_media/home/templates/home/update.html
{% extends 'base.html' %}

{% block title %}

    update Post

{% endblock title %}



{% block content %}

<form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value='update'>

</form>


{% endblock content %}